---
- name: Download Visual Studio Code Zip
  win_get_url:
    url: https://go.microsoft.com/fwlink/?Linkid=850641
    dest: C:\Users\{{ ansible_user }}\Downloads\vs-code.zip

- name: Unzip Visual Studio Code
  win_unzip:
    src: C:\Users\{{ ansible_user }}\Downloads\vs-code.zip
    dest: C:\Users\{{ ansible_user }}\Downloads\vs-code
    creates: C:\Users\{{ ansible_user }}\Downloads\vs-code
