---
- name: Download Visual Studio Code Exe
  win_get_url:
    url: https://go.microsoft.com/fwlink/?Linkid=852157
    dest: C:\Users\{{ ansible_user }}\Downloads\vs_code-install.exe
- name: Install Visual Studio Code
  win_package:
    path: C:\Users\{{ ansible_user }}\Downloads\vs_code-install.exe
    state: present
